        {
            "name": "slate",
            "background": "<%= slate0 %>",
            "foreground": "<%= slate6 %>",
            "black": "<%= slate1 %>",
            "red": "<%= slate11 %>",
            "green": "<%= slate14 %>",
            "yellow": "<%= slate13 %>",
            "blue": "<%= slate9 %>",
            "purple": "<%= slate15 %>",
            "cyan": "<%= slate8 %>",
            "white": "<%= slate5 %>",
            "brightBlack": "<%= slate3 %>",
            "brightRed": "<%= slate11 %>",
            "brightGreen": "<%= slate14 %>",
            "brightYellow": "<%= slate13 %>",
            "brightBlue": "<%= slate9 %>",
            "brightPurple": "<%= slate15 %>",
            "brightCyan": "<%= slate7 %>",
            "brightWhite": "<%= slate6 %>"
        }
